collections:
  machinelearning:
    output: true
  stats:
    output: true

defaults:
- scope:
    path: ""
    type: "machinelearning"
  values:
    layout: "math"
- scope:
    path: ""
    type: "stats"
  values:
    layout: "math"
- scope:
    path: ""
  values:
    layout: "default"
